plugins { id 'com.android.application' }
android {
    namespace 'com.efkagames.kulyagmuru'
    compileSdk 34
    defaultConfig {
        applicationId 'com.efkagames.kulyagmuru'
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName '0.9'
    }
    buildTypes { debug { minifyEnabled false } }
    // the game's images are already compressed
    androidResources { noCompress += ['jpg', 'png', 'webp'] }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
}
dependencies { implementation 'androidx.webkit:webkit:1.11.0' }
